apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-a4-setting
spec:
  forms:
    - group: basic
      label: 基础设置
      formSchema:
        - $formkit: text
          name: siteName
          label: 网站名称
          value: A4 Theme
